name: fmp_common
description: Shared resources for admin app and user app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

# ----------------------

dependencies:
  fmp_question_service_api:
    path: ../fmp_question_service_api
  fmp_questionnaire_service_api:
    path: ../fmp_questionnaire_service_api
  fmp_user_property_service_api:
    path: ../fmp_user_property_service_api
  fmp_exercise_service_api:
    path: ../fmp_exercise_service_api

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  json_annotation: ^4.3.0 # flutter pub run build_runner build
  video_player: 2.4.7

  #for password cache
  flutter_secure_storage: ^5.0.2
  shared_preferences:
  # for body map
  svg_path_parser: ^1.1.1
  touchable: ^1.0.0
  xml: ^5.3.1
  openapi_generator: ^3.3.0+1
  uuid: 3.0.6

# ----------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

  flutter_lints: ^1.0.0

# ----------------------

flutter:
  uses-material-design: true

  assets:
    - assets/img/fmp_logo.png
    - assets/img/undraw_finish_line.png

  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Thin.ttf
          weight: 100
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LexendDeca/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LexendDeca/LexendDeca-Black.ttf
          weight: 900

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
